# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [24]:
# Create and solve the relevant system of equations
# 29c + 41t = 490
# 23c + 41t = 448
import numpy as np
A = np.matrix('29 41; 23 41')
B = np.matrix('490; 448')

# Calculate inverse of A and take the dot product
A_inv = np.linalg.inv(A)
print(A_inv)
print(B)
X = A_inv.dot(B)
print(X)

# Verify the answer linalg.solve()
np.linalg.solve(A, B)

[[ 0.16666667 -0.16666667]
 [-0.09349593  0.11788618]]
[[490]
 [448]]
[[7.]
 [7.]]


matrix([[7.],
        [7.]])

In [16]:
np.matrix('29 41; 23 41')

matrix([[29, 41],
        [23, 41]])

In [17]:
np.matrix([[29, 41], [23, 41]])

matrix([[29, 41],
        [23, 41]])

In [4]:
A.dot(x) # matches answer

matrix([[490.],
        [448.]])

In [ ]:
# Describe your result
# Each bag costs $7

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [5]:
# Create and solve the relevant system of equations
# 12c + 3a = 162
# 8c + 3a = 122
A = np.matrix('12 3; 8 3')
B = np.matrix('162; 122')

x = np.linalg.solve(A, B)
print(x)

A.dot(x) #gives back B matrix, so correct x is correct

[[10.]
 [14.]]


matrix([[162.],
        [122.]])

In [ ]:
# Describe your result
# For each child, admission cost $10 and, for each, adult, admission cost $14

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [8]:
# Create and solve the relevant system of equations
# 5.25 = 0.5*O + 0.75*t + 1.25*c
# 7 = O + t + c
# 0 = -2*O + t

A = np.matrix('0.5 0.75 1.25; 1 1 1; -2 1 0')
B = np.matrix('5.25; 7; 0')
x = np.linalg.solve(A, B)
print(x)
A.dot(x) #gives back B maxtrix, so correct x is correct

[[2.]
 [4.]
 [1.]]


matrix([[5.25],
        [7.  ],
        [0.  ]])

In [ ]:
# Describe your result
# 2 onions, 4 tomatoes, and 1 carrot are in the soup

## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [9]:
# Create and solve the relevant system of equations
# B + BB + BBB = 1240
# 0.10B + 0.20BB + 0.30BBB = 276
# -2B + BBB = 0
A = np.matrix('1 1 1; 0.10 0.20 0.30; -2 0 1')
B = np.matrix('1240; 276; 0')
x = np.linalg.solve(A,B)
print(x)
A.dot(x) #gives back B maxtrix, so correct x is correct

[[280.]
 [400.]
 [560.]]


matrix([[1240.],
        [ 276.],
        [   0.]])

In [10]:
# Describe your result
# The rent for the 1B is $280, for the 2B is $400 and the 3B is $560

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 